# NOTE: "2" sets each rule to "error" level.
files:
  include: "_sass/**/*.scss"
options:
  formatter: "stylish"
  merge-default-rules: true
rules:
  force-attribute-nesting:
    - 2
  force-element-nesting:
    - 2
  force-pseudo-nesting:
    - 2
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations:
    - 2
    - include: true
  no-duplicate-properties:
    - 2
    - exclude:
      - max-width
      - width
  no-misspelled-properties:
    - 2
    - extra-properties:
      - -o-font-feature-settings
  no-qualifying-elements:
    - 2
  no-trailing-zero:
    - 2
  no-vendor-prefixes:
    - 2
  property-sort-order:
    - 2
  quotes:
    - 2
    - style: double
  space-around-operator:
    - 2
