files:
  include: "_sass/**/*.scss"
options:
  formatter: "stylish"
  merge-default-rules: true
rules:
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations:
    - 2
    - include: true
  no-duplicate-properties:
    - 2
    - exclude:
      - max-width
      - width
  no-misspelled-properties:
    - 2
    - extra-properties:
      - -o-font-feature-settings
  no-trailing-zero:
    - 2
  no-vendor-prefixes:
    - 2
  quotes:
    - 2
    - style: double
