# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
bundler_args: --without development
env:
  global:
  # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
before_install:
  - npm install -g sass-lint htmllint-cli markdownlint-cli
script:
  - JEKYLL_ENV=production bundle exec jekyll build
  - htmllint _includes/stripped_markdown.html
  - markdownlint _posts _drafts _pages README.md
  - sass-lint --verbose --no-exit
  - bundle exec htmlproofer --allow-hash-href --url-ignore "/localhost/" --assume-extension ./_site
