# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
os: linux
dist: bionic
language: ruby
cache: bundler
rvm:
  - 3.0.2
bundler_args: --without development
before_install:
  - rvm get stable
  - nvm install 16.4.2
  - nvm use 16.4.2
  - gem update --system
  - gem install bundler
env:
  global:
    # speeds up installation of htmlproofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      # Needed for htmlproofer external link checks
      - libcurl4-openssl-dev
      # Added for "Peer certificate cannot be authenticated with given
branches:
  only:
    - release
jobs:
  include:
    - stage: Test
      before_script:
        - npm install --global sass-lint htmllint-cli markdownlint-cli
      script:
        - JEKYLL_ENV=production bundle exec jekyll build
        - htmllint _includes/stripped_markdown.html
        - markdownlint _posts _drafts _pages README.md
        - sass-lint --verbose --no-exit
        # Explanations for flags:
        # --allow-hash-href - Build will fail on the first and last post entries
        # if this isn't allowed since there will be previous and next buttons
        # that have 'links to nowhere'.
        # --assume-extension - Jekyll 3 supports extensionless URLs, and
        # the blog uses them, so this flag needs to be here to prevent errors.
        # --url-ignore "/localhost/" - Posts have explicit references to
        # localhost, so don't consider them proper external links that need to
        # go anywhere.
        # --http-status-ignore "999" - LinkedIn doesn't seem to like crawlers,
        # and hence sends back 999 errors, even if the link is valid.
        # --disable-external - Only use this if the build fails unreasonably on
        # external links
        # NOTE: If a new post is created or new tags are introduced via a post,
        # htmlproofer will need to be disabled for a build in order to proceed
        # forward
        # NOTE 2: It would seem that there is an issue with checking Facebook
        # share links on Travis CI, so for the time beeing, ignore them since
        # they're generated by the blog theme and so out of my control anyway.
        # NOTE 3: It would seem that free-tier Heroku sites return a timeout if
        # they're not active, so don't bother checking their validity anymore
        # since there is a high chance they'll be too slow to respond.
        # NOTE 4: The minimal-mistakes-generated 404 page seems to have a #main
        # hash href to nowhere, so ignore all #main hash links for now; I don't
        # have any that I've created in any pages that I control.
        - >
          bundle exec htmlproofer _site
          --allow-hash-href
          --assume-extension
          --url-ignore "/localhost/,/facebook.com\/sharer\/sharer.php/,/herokuapp/,#main"
          --http-status-ignore "999"
          --typhoeus-config '{"ssl_verifypeer": false, "ssl_verifyhost": 0}'
          --disable-external
    - stage: Github Release
      script:
        - JEKYLL_ENV=production bundle exec jekyll build
      # Use dpl v2
      # https://docs.travis-ci.com/user/deployment-v2
      # https://docs.travis-ci.com/user/deployment-v2/providers/pages/
      deploy:
        provider: "pages:git"
        edge: true
        local_dir: "./_site"
        target_branch: master
        name: Travis Deployment Bot
        # This token generated at https://github.com/settings/tokens and added
        # to Travis environment variables.
        token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: release
