# References:
# - https://docs.travis-ci.com/user/caching/#Bundler
sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.5.3
bundler_args: --without development
env:
  global:
  # speeds up installation of html-proofer
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
branches:
  only:
    - release
before_install:
  - npm install -g sass-lint htmllint-cli markdownlint-cli
jobs:
  include:
    - script:
      - JEKYLL_ENV=production bundle exec jekyll build --destination site
      - htmllint _includes/stripped_markdown.html
      - markdownlint _posts _drafts _pages README.md
      - sass-lint --verbose --no-exit
      - bundle exec htmlproofer --allow-hash-href --url-ignore "/localhost/" --assume-extension ./_site
    - stage: Github Release
      deploy:
        provider: releases
        local-dir: ./site
        target-branch: master
        name: Deployment Bot
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: release
