# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Floor and Varnish
author: Paul Fioravanti
email: paul.fioravanti@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Text on a screen, usually with a technical bent.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://paulfioravanti.com
twitter_link: https://www.twitter.com/paulfioravanti
github_link:  https://github.com/paulfioravanti
linkedin_link: https://www.linkedin.com/in/paulfioravanti
stackoverflow_link: https://stackoverflow.com/users/567863
gravatar_link: https://s.gravatar.com/avatar/abda861707b1e78e0fce47ced55f84ee
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji

minima:
  date_format: "%b %-d, %Y"

disqus:
  shortname: paulfioravanti

google_analytics: "UA-109270947-1"

twitter:
  username: paulfioravanti

font_awesome_embed_code: 04ac649a83

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
# - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
