# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin  : "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Floor and Varnish"
title_separator          : "|"
name                     : "Paul Fioravanti"
description              : "The permanent drafts folder for brain dumps of Paul Fioravanti"
url                      : "https://www.paulfioravanti.com"
baseurl                  : "" # NOTE: This _needs_ to be an empty string, and not blank (`nil`)
repository               : "paulfioravanti/paulfioravanti.github.io"
teaser                   : "/assets/images/paul-teaser.jpg"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "paulfioravanti"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : true
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : "paulfioravanti"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/assets/images/paul-og.jpg"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/paulfioravanti"
    - "https://www.linkedin.com/in/paulfioravanti"
    - "https://github.com/paulfioravanti"
    - "https://stackoverflow.com/users/567863/paul-fioravanti"

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-109270947-1"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Paul Fioravanti"
  avatar           : "https://s.gravatar.com/avatar/abda861707b1e78e0fce47ced55f84ee"
  bio              : ":heart: code / :heart: languages :it: :jp: / :heart: mech :keyboard: / Learning stenography"
  location         : "Sydney, Australia"
  email            : "paul@paulfioravanti.com"
  uri              : "https://www.paulfioravanti.com"
  home             : "/"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "paulfioravanti"
  gitlab           :
  google_plus      :
  keybase          : "paulfioravanti"
  instagram        :
  lastfm           :
  linkedin         : "paulfioravanti"
  pinterest        :
  soundcloud       :
  stackoverflow    : "567863/paul-fioravanti"
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          : "paulfioravanti"
  vine             :
  weibo            :
  xing             :
  youtube          : "https://www.youtube.com/channel/UC_ObnUGtIfRRq6vbxFYRpUg"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Australia/Sydney


# Plugins (previously gems:)
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
tag_archive:
  type: "jekyll-archives"
  path: "/tags/"
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - "tags"
  layouts:
    tag: "archive-taxonomy"
  permalinks:
    tag: "/tags/:name/"


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      # https://mmistakes.github.io/minimal-mistakes/markup-text-readability-wide-page/
      classes: wide
      comments: true
      # https://jekyllrb.com/docs/posts/#post-excerpts
      excerpt_separator: "<!--more-->"
      layout: single
      read_time: true
      related: true
      share: true
      show_date: true
      signup: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      classes: wide
      layout: single
      show_date: true
      signup: true

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]
