name: CI
on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # speeds up installation of htmlproofer
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Set up Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Global npm packages
        run: npm install --location=global sass-lint htmllint-cli markdownlint-cli

      - name: Run htmllint
        run: htmllint _includes/japanese/* _includes/ruby/* _includes/audio-narration-banner.html _includes/audio-profile-custom-links.html _includes/japanese.html _includes/ruby.html _includes/signup-form.html _includes/stripped_markdown.html

      - name: Run markdownlint
        run: markdownlint _posts _drafts _pages README.md

      - name: Run sass-lint
        run: sass-lint --verbose --no-exit

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build

      # Explanations for flags:
      # --allow-hash-href - Build will fail on the first and last post entries
      # if this isn't allowed since there will be previous and next buttons
      # that have 'links to nowhere'.
      # --assume-extension - Jekyll 3 supports extensionless URLs, and
      # the blog uses them, so this flag needs to be here to prevent errors.
      # --url-ignore "/localhost/" - Posts have explicit references to
      # localhost, so don't consider them proper external links that need to
      # go anywhere.
      # --ignore-status-codes "999" - LinkedIn doesn't seem to like crawlers,
      # and hence sends back 999 errors, even if the link is valid.
      # --disable-external - Only use this if the build fails unreasonably on
      # external links
      # NOTE: If a new post is created or new tags are introduced via a post,
      # htmlproofer will need to be disabled for a build in order to proceed
      # forward
      # NOTE 2: It would seem that there is an issue with checking Facebook
      # share links on Travis CI, so for the time beeing, ignore them since
      # they're generated by the blog theme and so out of my control anyway.
      # NOTE 3: It would seem that free-tier Heroku sites return a timeout if
      # they're not active, so don't bother checking their validity anymore
      # since there is a high chance they'll be too slow to respond.
      # NOTE 4: The minimal-mistakes-generated 404 page seems to have a #main
      # hash href to nowhere, so ignore all #main hash links for now; I don't
      # have any that I've created in any pages that I control.
      # NOTE X: It seems like htmlproofer has some Nokogiri-related issues.
      # Re-enable this when it's fixed...
      # - name: Run htmlproofer
      #   run: >
      #     bundle exec htmlproofer _site
      #     --allow-hash-href
      #     --assume-extension
      #     --ignore-urls "/localhost/,/facebook.com\/sharer\/sharer.php/,/herokuapp/,#main"
      #     --ignore-status-codes "999,429,403,0"
      #     --typhoeus '{"ssl_verifypeer": false, "ssl_verifyhost": 0}'
      #   # --disable-external

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: master
          folder: _site

